title: Nadia Zubko
logo: "/1633469688309-modified.png"
description:
 Frontend Developer
  <br><br>
  <a href="mailto:na-zubko@outlook.com">Email: na-zubko@outlook.com</a>
  <br>
  <a href="https://www.linkedin.com/in/https://www.linkedin.com/in/nadezhda-zubko-developer//"My LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/https://N-Zubko/">My GitHub Page</a> 
theme: jekyll-theme-minimal
