title: Nadia Zubko
logo: "/1633469688309-modified.png?raw=true"
description:
 Frontend Developer
  <br><br>
  <a href="mailto:na-zubko@outlook.com">Email: na-zubko@outlook.com</a>
  <br>
  <a href="https://www.linkedin.com/in/nadezhda-zubko-developer/">My LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/N-Zubko/">View My GitHub Page</a> 
theme: jekyll-theme-minimal
