title: Nadia Zubko
logo: "/1633469688309-modified.png=true"
description:
 Frontend Developer
  <br><br>
  <a href="mailto:na-zubko@outlook.com">na-zubko@outlook.com</a>
  <br>
  <a href="https://www.linkedin.com/in/https://www.linkedin.com/in/nadezhda-zubko-developer//">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/https://N-Zubko/">Gihub</a> 
theme: jekyll-theme-minimal
